// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZik-eXjetCykbDny82m3r_2WDiFB6s40',
    appId: '1:1824075632:web:3e5c77e649da5d30dd69b5',
    messagingSenderId: '1824075632',
    projectId: 'online-store-nsra',
    authDomain: 'online-store-nsra.firebaseapp.com',
    storageBucket: 'online-store-nsra.appspot.com',
    measurementId: 'G-CYS3195JDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1gEvSTUeRwUKc_GCNnZGfOwzdzKmqOg',
    appId: '1:1824075632:android:612551056a5d51f2dd69b5',
    messagingSenderId: '1824075632',
    projectId: 'online-store-nsra',
    storageBucket: 'online-store-nsra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35aAk4BXNYvO3_PJYZ2gt6lA5MdTkzco',
    appId: '1:1824075632:ios:68f57a0303763e07dd69b5',
    messagingSenderId: '1824075632',
    projectId: 'online-store-nsra',
    storageBucket: 'online-store-nsra.appspot.com',
    iosBundleId: 'com.example.flutterApplicationCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD35aAk4BXNYvO3_PJYZ2gt6lA5MdTkzco',
    appId: '1:1824075632:ios:d5bc389580be3088dd69b5',
    messagingSenderId: '1824075632',
    projectId: 'online-store-nsra',
    storageBucket: 'online-store-nsra.appspot.com',
    iosBundleId: 'com.example.flutterApplicationCommerce.RunnerTests',
  );
}
